<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    public function findAllGroupedByCode()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->getQuery()
            ->getResult();
    }
}
